### PR TITLE
Support Global Menus

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Closes https://github.com/flathub/com.microsoft.Edge/issues/100.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
bot, build

**Comment by tinywrkb** [comment]
I don't think this is going to work. I have Kinoite installed on an old laptop, let me see if I can get something working.

**Comment by tinywrkb** [comment]
Actually, this solves it, as far as I can tell.  
It's a bit confusing at first, as the menus won't appear at startup, but if you switch to another window, then it will work correctly.  
I thought I would need the`appmenu-gtk-module` like [this](https://github.com/tinywrkb/com.microsoft.Edge/commit/634a41b82396daec889a2d9f8b890a7c19992115), but it's actually not needed.

**Comment by tinywrkb** [comment]
p.s. https://github.com/tinywrkb/com.microsoft.Edge/commit/d5562fe227c4e204dda356824973bd0c6d5c4f42

**Comment by TheEvilSkeleton** [comment]
@tinywrkb are you suggesting to drop https://github.com/flathub/com.microsoft.Edge/blob/d729e5ab02a8a7a6c14c5e04025c8bdfa56234bc/com.microsoft.Edge.yaml#L69

altogether?

(Lol 69)

**Comment by tinywrkb** [comment]
Yes, drop it, and flatpak-builder even complains about it.

**Comment by TheEvilSkeleton** [comment]
https://github.com/flathub/com.microsoft.Edge/issues/100#issuecomment-999131483 reports that the test build is working as intended.

**Pull request merged**
