### PR TITLE
Switch to beta branch

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Closes https://github.com/flathub/com.microsoft.Edge/issues/37

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
@TuxKruger @tinywrkb @second2050 can you test it? Back up your `~/.var/app/com.microsoft.Edge` directory before testing it because the beta uses a lower version.

**Comment by TheEvilSkeleton** [comment]
```
Error: While trying to apply extra data: apply_extra script failed, exit status 256
error: Failed to install com.microsoft.Edge: While trying to apply extra data: apply_extra script failed, exit status 256
```

Lol, I probably messed something up

**Comment by tinywrkb** [comment]
Builds and installed correctly for me.  

```
edge://version

Microsoft Edge: 91.0.864.15 (Official build) dev (64-bit)
Revision | b341bc14fb852d1c3c6f095dec7423084ee4ab64
```

The desktop file and icon need to be updated.

**Comment by TuxKruger** [comment]
Seems to work on my side. I will report issues if I face any.

**Comment by TheEvilSkeleton** [comment]
Not entirely sure what's causing this:
image

**Comment by TheEvilSkeleton** [comment]
Okay, that seemed to fix the issue apparently. Everything looks good to me.

**Comment by tinywrkb** [comment]
No issue with Rofi.

swappy-20210505-185454

**Comment by TheEvilSkeleton** [comment]
I'm going to merge soon. If there is a problem, please do let me know.

**Comment by TheEvilSkeleton** [comment]
Thank you for testing!

**Pull request merged**
